---
# sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: epel
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:7
      MOLECULE_PLAYBOOK: manual_playbook.yml
    - MOLECULE_DISTRO: centos:7
      MOLECULE_PLAYBOOK: manual_baseurl_playbook.yml
    - MOLECULE_DISTRO: debian:stretch
    - MOLECULE_DISTRO: ubuntu:bionic

install:
  - pip install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME ericsysmin.$ROLE_NAME
  - cd ericsysmin.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
